set(_CATKIN_CURRENT_PACKAGE "genmobile")
set(genmobile_VERSION "0.4.0")
set(genmobile_MAINTAINER "Ronaldson Bellande <ronaldsonbellande@gmail.com>")
set(genmobile_PACKAGE_FORMAT "1")
set(genmobile_BUILD_DEPENDS "genmsg" "rosjava_build_tools" "python-catkin-pkg" "python-rospkg" "rosjava_bootstrap" "rosjava_build_tools")
set(genmobile_BUILD_EXPORT_DEPENDS "genmsg" "rosjava_build_tools" "python-catkin-pkg" "python-rospkg" "rosjava_bootstrap" "rosjava_build_tools")
set(genmobile_BUILDTOOL_DEPENDS "catkin")
set(genmobile_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(genmobile_BUILDTOOL_EXPORT_DEPENDS )
set(genmobile_EXEC_DEPENDS "genmsg" "rosjava_build_tools" "python-catkin-pkg" "python-rospkg" "rosjava_bootstrap" "rosjava_build_tools")
set(genmobile_RUN_DEPENDS "genmsg" "rosjava_build_tools" "python-catkin-pkg" "python-rospkg" "rosjava_bootstrap")
set(genmobile_TEST_DEPENDS )
set(genmobile_DOC_DEPENDS )
set(genmobile_URL_WEBSITE "http://www.ros.org/wiki/genmobile")
set(genmobile_URL_BUGTRACKER "https://github.com/rosjava/genmobile/issues")
set(genmobile_URL_REPOSITORY "https://github.com/rosjava/genmobile")
set(genmobile_DEPRECATED "")