set(genjava_SETUP_PY_SETUP_MODULE "distutils.core")
set(genjava_SETUP_PY_VERSION "0.4.0")
set(genjava_SETUP_PY_SCRIPTS "scripts/genjava_message_artifacts")
set(genjava_SETUP_PY_PACKAGES "genjava")
set(genjava_SETUP_PY_PACKAGE_DIRS "src/genjava")
set(genjava_SETUP_PY_MODULES "")
set(genjava_SETUP_PY_MODULE_DIRS "")